AWSTemplateFormatVersion: 2010-09-09
Description: Deploy Benchmark Flask app to ECS Fargate with ALB (ov3 version)

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Use default VPC
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Use subnets in us-east-1a and us-east-1b

Resources:

  FargateBenchmarkOv3SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access to benchmark app (ov3)
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  FargateBenchmarkOv3LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/fargate-benchmark-ov3
      RetentionInDays: 7

  FargateBenchmarkOv3ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: fargate-benchmark-alb-ov3
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref FargateBenchmarkOv3SecurityGroup
      Type: application

  FargateBenchmarkOv3TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: fargate-benchmark-tg-ov3
      Port: 5000
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /health
      Matcher:
        HttpCode: 200
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  FargateBenchmarkOv3Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref FargateBenchmarkOv3ALB
      Port: 5000
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FargateBenchmarkOv3TargetGroup

  FargateBenchmarkOv3Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: fargate-benchmark-cluster-ov3

  FargateBenchmarkOv3TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fargate-benchmark-task-ov3
      Cpu: '256'
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::634914382615:role/flask-fargate-execution
      ContainerDefinitions:
        - Name: benchmark-container-ov3
          Image: 634914382615.dkr.ecr.us-east-1.amazonaws.com/fargate-benchmark:latest
          PortMappings:
            - ContainerPort: 5000
              Protocol: tcp
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/fargate-benchmark-ov3
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs

  FargateBenchmarkOv3Service:
    Type: AWS::ECS::Service
    DependsOn: FargateBenchmarkOv3Listener
    Properties:
      ServiceName: fargate-benchmark-service-ov3
      Cluster: !Ref FargateBenchmarkOv3Cluster
      TaskDefinition: !Ref FargateBenchmarkOv3TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref FargateBenchmarkOv3SecurityGroup
          Subnets: !Ref SubnetIds
      LoadBalancers:
        - ContainerName: benchmark-container-ov3
          ContainerPort: 5000
          TargetGroupArn: !Ref FargateBenchmarkOv3TargetGroup
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true

Outputs:
  LoadBalancerDNSOv3:
    Description: DNS name of the load balancer (ov3)
    Value: !GetAtt FargateBenchmarkOv3ALB.DNSName
